### PR TITLE
Duolingo  Liberia

### PR DESCRIPTION
**Pull request by Fullchord**
-makes Duolingo as the leader on non aligned Liberia

### CODE REVIEW

**Comment by Fullchord** [comment]
image

**Review by atomicplan666 — CHANGES_REQUESTED** [review]
absolutely disgusting

**Comment by Popcorn371** [comment]
+

**Review by Endsiegg — APPROVED** [review]
Meme worthy

**Review by xfrenzzyy — APPROVED** [review]

**Comment by atomicplan666** [comment]
image

This image should be the portrait

**Review by atomicplan666 — APPROVED** [review]
fuck it

**Pull request merged**
