### PR TITLE
Poland Rebalance

### PR DESCRIPTION
**Pull request by Fullchord**
-changed some starting division's equipment factor(slightly less)
-changed a few OP starting div templates to "default" templates (less arty, small increase in inf)
-nerfed total starting arty from 3.3K to 2.3K at START (33% NERF)
-added support aa to one template to use up some wasted stockpile (800k un-used in aug 38) (AI would produce for some reason not ever use in template)
-merged air wings (200 fighters, 100 CAS TOTAL (prevents Ai from wasting mills on air)(small round up))
-made Poland only have four mils on air the entire game
-slightly increased supp equip (200 from 150) (still has 400 deficit at the start)

### CODE REVIEW

**Comment by Fullchord** [comment]
JAN 38 stock
image

**Comment by Fullchord** [comment]
JAN 36 stock
image

**Comment by Fullchord** [comment]
AUG 37 STOCK
image

**Comment by Fullchord** [comment]
OLD (live version) 36 stockpile
image

**Review by xfrenzzyy — APPROVED** [review]
I'd be cool with this, the only problem I see is they start with 3k extra guns not sure where that comes from. But, it might balance out because they have 1k less artillery. I'll be cool with pushing this to live server and testing it out.

**Comment by atomicplan666** [comment]
image

Poland after deleting divisions in vanilla 1936

**Comment by atomicplan666** [comment]
image

Poland before deleting divisions in vanilla 1936

**Comment by atomicplan666** [comment]
I'm going to close this pull request until we've looked at the other pull request that's a little more intense.

**Comment by Fullchord** [comment]
THis is what poland should be

**Pull request closed without merging**
