### PR TITLE
Japan and Manchu additions

### PR DESCRIPTION
**Pull request by Juddur**
Fixes Manchuria, adds to non-aligned and democratic Japan paths. Reworks Manchu investment tree. Adds TONS of new GFX and localization for Manchu and Japan

### CODE REVIEW

**Review by xfrenzzyy — COMMENTED** [review]
Everything looks fine other than the Pakistan stuff, I thought Pakistan gets RAJ Caste System, but they don't get the unification bullshit?

**Review by Fullchord — COMMENTED** [review]
I made Pakistan have the unification as a request from Gandhi as a compromise to avoid just completely removing the formable, which is what I originally wanted to do. So this is by design.

**Comment by xfrenzzyy** [comment]
So Pakistan is perma debuffed, and -450 pp on top of losing like 150 days it takes to do the unification. Makes sense

**Comment by xfrenzzyy** [comment]
Only reason I'm saying this is because that nation gains no pp in its tree so the -450 pp is gamechanging for that nation.

**Review by xfrenzzyy — APPROVED** [review]

**Review by Fullchord — APPROVED** [review]
I like the gfx

**Review by jgDarkWolf — APPROVED** [review]
👍🏻

**Review by atomicplan666 — APPROVED** [review]
looks good

**Pull request merged**
